## @file config.toml
## @brief Konfiguration für den Nutzer Stefan .

- handle: "Stefan" -> Name dieses Clients  
- port: 5000 –> Empfangsport für Nachrichten  
- whoisport: 4000 –> Port für WHOIS-Anfragen  
- autorepli: "Ich bin gerade nicht da." –> Nachricht bei Abwesenheit  
- imagepath: "./images" –> Pfad zu Bilddateien, die gesendet werden können  


handle = "Stefan"
port = 5001
 whoisport = 4000
 imagepath = "./images"