## \file config.toml
## \brief Konfiguration für den Nutzer Altay.

handle: "Altay" –> Name dieses Clients  
port: 5003 – >Port für eingehende Nachrichten  
whoisport: 4000 – >Port für WHOIS-Anfragen  
autoreply: "Ich bin gerade nicht da." –> Automatische Antwort bei Abwesenheit  
imagepath: "./images" –> Pfad zum Bildordner 



handle = "Altay"
port = 5003
whoisport = 4000
autoreply = "Ich bin gerade nicht da."
imagepath = "./images"

###Zielnutzer: 

[ayman]
ziel_name = "ayman"
ziel_port = "5000"
ziel_ip = "172.20.10.14"

[ayman2]
ziel_name = "ayman2"
ziel_port = "55033"
ziel_ip = "172.20.10.14"


