handle = "Tom"
port = 5001
whoisport = 4000
autoreply = "Ich bin gerade nicht da."
imagepath = "./images"

[login_daten]
name = "Tom"
port = 5001
whoisport = 4000
ip = "127.0.0.1"
ipnetz = "255.255.255.255"
hallo = "Ich bin gerade nicht da."
