handle = "Ayman"
port = 5000
whoisport = 4000
autoreply = "Ich bin gerade nicht da."
imagepath = "./images"


[login_daten]
name = "Ayman"
port = "5000"
ip = "10.0.0.1"
ipnetz = "255.255.255.255"
hallo = "Hi, ich bin Ayman"
whoisport = 4000